ALTER TABLE developers ADD COLUMN salary REAL;
UPDATE developers SET salary = '500' WHERE id='1';
UPDATE developers SET salary = '1000' WHERE id='2';
UPDATE developers SET salary = '1300' WHERE id='3';
UPDATE developers SET salary = '1000' WHERE id='4';
UPDATE developers SET salary = '1500' WHERE id='5';
UPDATE developers SET salary = '1500' WHERE id='6';
UPDATE developers SET salary = '1200' WHERE id='7';
UPDATE developers SET salary = '1300' WHERE id='8';
UPDATE developers SET salary = '1000' WHERE id='9';
UPDATE developers SET salary = '900' WHERE id='10';
UPDATE developers SET salary = '1200' WHERE id='11';
UPDATE developers SET salary = '900' WHERE id='12';
UPDATE developers SET salary = '800' WHERE id='13';
UPDATE developers SET salary = '1500' WHERE id='14';
UPDATE developers SET salary = '1800' WHERE id='15';